### PR TITLE
fix(wizard): improve documentation 

### LINKED ISSUE #860: [wc:wizard] Improve documentation
As a developper the wizard documentation doesn't provide the list of api available to know how to use it.
Example of documentation expected [API - Properties/Attributes](https://github.com/material-components/material-web/tree/mwc/packages/textfield#api)

### PR DESCRIPTION
**Pull request by dorsaffrigui**
fix #860

- improve doc
- Manage the case when all next steps or back steps are disabled

### CODE REVIEW

File: libs/web-components/wizard/src/wizard.ts [hunk 1]
```diff
@@ -234,6 +250,10 @@ export class Wizard extends LitElement {
   }
 
   _handleNextClick() {
+    if(this.CheckIfAllNextStepsDisabled(this.currentStepIndex)) {
+      throw new Error('The wizard has no next page to go to.');
```
Comment (bcldvd) [inline libs/web-components/wizard/src/wizard.ts:254]: Don't think it's necessary to throw an error here. Just don't do the rest :)

**Comment by Pi5rr5** [comment]
Wizard is not displayed in storybook 
image

image

**Comment by dorsaffrigui** [comment]
> Wizard is not displayed in storybook image
> 
> image

Resolved

**Review by ttalbot — APPROVED** [review]

**Review by Pi5rr5 — APPROVED** [review]
