### PR TITLE
bugfix#847 fix item bar size

### LINKED ISSUE #847: [Icon bar]: change icon bar item size
**Describe the bug**
fds-icon-bar-item size shoud be 32 * 32, actual size is 38 * 38.

**Screenshots**

Screenshot 2022-08-24 at 11 03 55

### PR DESCRIPTION
**Pull request by Pi5rr5**
Fix #847

### CODE REVIEW

File: libs/web-components/icon-bar/src/icon-bar.ts [hunk 1]
```diff
@@ -18,16 +18,16 @@ export class IconBar extends LitElement {
   @property({ type: Boolean }) large = false;
```
Comment (dorsaffrigui) [inline libs/web-components/icon-bar/src/icon-bar.ts:18]: Could you please change the name "large" to "withLabels" ?

Comment (Pi5rr5) [reply libs/web-components/icon-bar/src/icon-bar.ts]: Changed for showLabels to keep the logic of show/hide.

**Review by dorsaffrigui — APPROVED** [review]

**Review by ttalbot — APPROVED** [review]
